"""Token remove to invalidate

Revision ID: fb120f8fc198
Revises: 8188d671489a
Create Date: 2023-07-25 11:39:26.423122

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "fb120f8fc198"
down_revision = "8188d671489a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("token", "authenticates_id",
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column("token", "is_valid")
    op.alter_column("user", "created",
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("now()"))
    op.alter_column("user", "modified",
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("now()"))
    op.alter_column("user", "email_validated",
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column("user", "is_active",
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column("user", "is_superuser",
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "is_superuser",
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column("user", "is_active",
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column("user", "email_validated",
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column("user", "modified",
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("now()"))
    op.alter_column("user", "created",
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("now()"))
    op.add_column("token", sa.Column("is_valid", sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column("token", "authenticates_id",
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
